Updates to easelJS demos
AlphaMaskReveal - Filter not working
APITest - TOC need to be included / Stroke samples broken
BarGraph - Stroke issue
BitmapText  - good
ButtonHelper - MC issue / initialize is not a function
Cache_update - good
Cache_vday - good
Cache - good
CurveTo - good
DOMElement - good
DoubleClickTest - good
DragAndDrop_hitArea - good
DragAndDrop - good
EventBubbling - good
Filters_animated - good
Filters_input - Slider issue / extend
Filters_simple - good
GlobalToLocal1 - good
GlobalToLocal2 - HSLA issue
Graphics_setStrokeDash - stroke issue
Graphics_simple - good
Graphics_winding - good
GraphicsReuse - good
GraphicsTest - good
GraphicsTestTiny - good
HelloWorld - good
Icons - good
LocalToGlobal - good
Masks - good
RollOverMouseOver - good
Sparkles - good
SpriteSheet_simple - good
SpriteSheetBuilder - good
Text_links - createjs.extends
Text_multiline - good
Text_simple - good
Transform_simple - good
Transform - Slider issue / extend
TwoStages - good

Game - createjs.extends
SpriteSheetBuilder_MovieClip - movieClip issue

//WebGL
Benchmark - preload issue
HelloWorld - StageGL.js:29 Uncaught SyntaxError: Unexpected identifier
Runners - StageGL.js:125 Uncaught TypeError: Cannot read property 'preserveBuffer' of undefined
Sparkles -  StageGL.js:29 Uncaught SyntaxError: Unexpected identifier
SystemInfo - StageGL.js:29 Uncaught SyntaxError: Unexpected identifier
TwoStages - StageGL.js:29 Uncaught SyntaxError: Unexpected identifier